# 1 Titanic<br>


### Load dataset

In [2]:
val titaticDF = spark
                .read
                .format("csv")
                .option("header", "true")
                .option("inferSchema", "true")
                .load("../datasets/titanic/titanic3.csv")

titaticDF.show(400)

+------+--------+--------------------+------+------+-----+-----+----------------+--------+---------------+--------+----+----+--------------------+
|pclass|survived|                name|   sex|   age|sibsp|parch|          ticket|    fare|          cabin|embarked|boat|body|           home.dest|
+------+--------+--------------------+------+------+-----+-----+----------------+--------+---------------+--------+----+----+--------------------+
|     1|       1|Allen, Miss. Elis...|female|  29.0|    0|    0|           24160|211.3375|             B5|       S|   2|null|        St Louis, MO|
|     1|       1|Allison, Master. ...|  male|0.9167|    1|    2|          113781|  151.55|        C22 C26|       S|  11|null|Montreal, PQ / Ch...|
|     1|       0|Allison, Miss. He...|female|   2.0|    1|    2|          113781|  151.55|        C22 C26|       S|null|null|Montreal, PQ / Ch...|
|     1|       0|Allison, Mr. Huds...|  male|  30.0|    1|    2|          113781|  151.55|        C22 C26|       S|null| 135|Montreal, PQ / Ch...|
|     1|       0|Allison, Mrs. Hud...|female|  25.0|    1|    2|          113781|  151.55|        C22 C26|       S|null|null|Montreal, PQ / Ch...|
|     1|       1| Anderson, Mr. Harry|  male|  48.0|    0|    0|           19952|   26.55|            E12|       S|   3|null|        New York, NY|
|     1|       1|Andrews, Miss. Ko...|female|  63.0|    1|    0|           13502| 77.9583|             D7|       S|  10|null|          Hudson, NY|
|     1|       0|Andrews, Mr. Thom...|  male|  39.0|    0|    0|          112050|     0.0|            A36|       S|null|null|         Belfast, NI|
|     1|       1|Appleton, Mrs. Ed...|female|  53.0|    2|    0|           11769| 51.4792|           C101|       S|   D|null| Bayside, Queens, NY|
|     1|       0|Artagaveytia, Mr....|  male|  71.0|    0|    0|        PC 17609| 49.5042|           null|       C|null|  22| Montevideo, Uruguay|
|     1|       0|Astor, Col. John ...|  male|  47.0|    1|    0|        PC 17757| 227.525|        C62 C64|       C|null| 124|        New York, NY|
|     1|       1|Astor, Mrs. John ...|female|  18.0|    1|    0|        PC 17757| 227.525|        C62 C64|       C|   4|null|        New York, NY|
|     1|       1|Aubart, Mme. Leon...|female|  24.0|    0|    0|        PC 17477|    69.3|            B35|       C|   9|null|       Paris, France|
|     1|       1|"Barber, Miss. El...|female|  26.0|    0|    0|           19877|   78.85|           null|       S|   6|null|                null|
|     1|       1|Barkworth, Mr. Al...|  male|  80.0|    0|    0|           27042|    30.0|            A23|       S|   B|null|       Hessle, Yorks|
|     1|       0| Baumann, Mr. John D|  male|  null|    0|    0|        PC 17318|  25.925|           null|       S|null|null|        New York, NY|
|     1|       0|Baxter, Mr. Quigg...|  male|  24.0|    0|    1|        PC 17558|247.5208|        B58 B60|       C|null|null|        Montreal, PQ|
|     1|       1|Baxter, Mrs. Jame...|female|  50.0|    0|    1|        PC 17558|247.5208|        B58 B60|       C|   6|null|        Montreal, PQ|
|     1|       1|Bazzani, Miss. Al...|female|  32.0|    0|    0|           11813| 76.2917|            D15|       C|   8|null|                null|
|     1|       0|Beattie, Mr. Thomson|  male|  36.0|    0|    0|           13050| 75.2417|             C6|       C|   A|null|        Winnipeg, MN|
|     1|       1|Beckwith, Mr. Ric...|  male|  37.0|    1|    1|           11751| 52.5542|            D35|       S|   5|null|        New York, NY|
|     1|       1|Beckwith, Mrs. Ri...|female|  47.0|    1|    1|           11751| 52.5542|            D35|       S|   5|null|        New York, NY|
|     1|       1|Behr, Mr. Karl Ho...|  male|  26.0|    0|    0|          111369|    30.0|           C148|       C|   5|null|        New York, NY|
|     1|       1|Bidois, Miss. Ros...|female|  42.0|    0|    0|        PC 17757| 227.525|           null|       C|   4|null|                null|
|     1|       1|   Bird, Miss. Ellen|female|  29.0|    0|    0|        PC 17483|221.7792|            C97|       S|   8|null|                null|
|     1|       0| Birnbaum, Mr. Jakob|  male|  25.0|    0|    0|           13905|    26.0|           null|       C|null| 148|   San Francisco, CA|
|     1|       1|Bishop, Mr. Dicki...|  male|  25.0|    1|    0|           11967| 91.0792|            B49|       C|   7|null|        Dowagiac, MI|
|     1|       1|Bishop, Mrs. Dick...|female|  19.0|    1|    0|           11967| 91.0792|            B49|       C|   7|null|        Dowagiac, MI|
|     1|       1|Bissette, Miss. A...|female|  35.0|    0|    0|        PC 17760|135.6333|            C99|       S|   8|null|                null|
|     1|       1|Bjornstrom-Steffa...|  male|  28.0|    0|    0|          110564|   26.55|            C52|       S|   D|null|Stockholm, Sweden...|
|     1|       0|Blackwell, Mr. St...|  male|  45.0|    0|    0|          113784|    35.5|              T|       S|null|null|         Trenton, NJ|
|     1|       1|    Blank, Mr. Henry|  male|  40.0|    0|    0|          112277|    31.0|            A31|       C|   7|null|      Glen Ridge, NJ|
|     1|       1|Bonnell, Miss. Ca...|female|  30.0|    0|    0|           36928|164.8667|             C7|       S|   8|null|      Youngstown, OH|
|     1|       1|Bonnell, Miss. El...|female|  58.0|    0|    0|          113783|   26.55|           C103|       S|   8|null|Birkdale, England...|
|     1|       0|Borebank, Mr. Joh...|  male|  42.0|    0|    0|          110489|   26.55|            D22|       S|null|null|London / Winnipeg...|
|     1|       1|Bowen, Miss. Grac...|female|  45.0|    0|    0|        PC 17608| 262.375|           null|       C|   4|null|     Cooperstown, NY|
|     1|       1|Bowerman, Miss. E...|female|  22.0|    0|    1|          113505|    55.0|            E33|       S|   6|null|St Leonards-on-Se...|
|     1|       1|"Bradley, Mr. Geo...|  male|  null|    0|    0|          111427|   26.55|           null|       S|   9|null|     Los Angeles, CA|
|     1|       0|Brady, Mr. John B...|  male|  41.0|    0|    0|          113054|    30.5|            A21|       S|null|null|         Pomeroy, WA|
|     1|       0|  Brandeis, Mr. Emil|  male|  48.0|    0|    0|        PC 17591| 50.4958|            B10|       C|null| 208|           Omaha, NE|
|     1|       0|Brewe, Dr. Arthur...|  male|  null|    0|    0|          112379|    39.6|           null|       C|null|null|    Philadelphia, PA|
|     1|       1|Brown, Mrs. James...|female|  44.0|    0|    0|        PC 17610| 27.7208|             B4|       C|   6|null|          Denver, CO|
|     1|       1|Brown, Mrs. John ...|female|  59.0|    2|    0|           11769| 51.4792|           C101|       S|   D|null|         Belmont, MA|
|     1|       1|Bucknell, Mrs. Wi...|female|  60.0|    0|    0|           11813| 76.2917|            D15|       C|   8|null|    Philadelphia, PA|
|     1|       1|Burns, Miss. Eliz...|female|  41.0|    0|    0|           16966|   134.5|            E40|       C|   3|null|                null|
|     1|       0|Butt, Major. Arch...|  male|  45.0|    0|    0|          113050|   26.55|            B38|       S|null|null|      Washington, DC|
|     1|       0|Cairns, Mr. Alexa...|  male|  null|    0|    0|          113798|    31.0|           null|       S|null|null|                null|
|     1|       1|Calderhead, Mr. E...|  male|  42.0|    0|    0|        PC 17476| 26.2875|            E24|       S|   5|null|        New York, NY|
|     1|       1|Candee, Mrs. Edwa...|female|  53.0|    0|    0|        PC 17606| 27.4458|           null|       C|   6|null|      Washington, DC|
|     1|       1|Cardeza, Mr. Thom...|  male|  36.0|    0|    1|        PC 17755|512.3292|    B51 B53 B55|       C|   3|null|Austria-Hungary /...|
|     1|       1|Cardeza, Mrs. Jam...|female|  58.0|    0|    1|        PC 17755|512.3292|    B51 B53 B55|       C|   3|null|Germantown, Phila...|
|     1|       0|Carlsson, Mr. Fra...|  male|  33.0|    0|    0|             695|     5.0|    B51 B53 B55|       S|null|null|        New York, NY|
|     1|       0|Carrau, Mr. Franc...|  male|  28.0|    0|    0|          113059|    47.1|           null|       S|null|null| Montevideo, Uruguay|
|     1|       0|Carrau, Mr. Jose ...|  male|  17.0|    0|    0|          113059|    47.1|           null|       S|null|null| Montevideo, Uruguay|
|     1|       1|Carter, Master. W...|  male|  11.0|    1|    2|          113760|   120.0|        B96 B98|       S|   4|null|       Bryn Mawr, PA|
|     1|       1|Carter, Miss. Luc...|female|  14.0|    1|    2|          113760|   120.0|        B96 B98|       S|   4|null|       Bryn Mawr, PA|
|     1|       1|Carter, Mr. Willi...|  male|  36.0|    1|    2|          113760|   120.0|        B96 B98|       S|   C|null|       Bryn Mawr, PA|
|     1|       1|Carter, Mrs. Will...|female|  36.0|    1|    2|          113760|   120.0|        B96 B98|       S|   4|null|       Bryn Mawr, PA|
|     1|       0|Case, Mr. Howard ...|  male|  49.0|    0|    0|           19924|    26.0|           null|       S|null|null|Ascot, Berkshire ...|
|     1|       1|Cassebeer, Mrs. H...|female|  null|    0|    0|           17770| 27.7208|           null|       C|   5|null|        New York, NY|
|     1|       0|Cavendish, Mr. Ty...|  male|  36.0|    1|    0|           19877|   78.85|            C46|       S|null| 172|Little Onn Hall, ...|
|     1|       1|Cavendish, Mrs. T...|female|  76.0|    1|    0|           19877|   78.85|            C46|       S|   6|null|Little Onn Hall, ...|
|     1|       0|Chaffee, Mr. Herb...|  male|  46.0|    1|    0|     W.E.P. 5734|  61.175|            E31|       S|null|null|          Amenia, ND|
|     1|       1|Chaffee, Mrs. Her...|female|  47.0|    1|    0|     W.E.P. 5734|  61.175|            E31|       S|   4|null|          Amenia, ND|
|     1|       1|Chambers, Mr. Nor...|  male|  27.0|    1|    0|          113806|    53.1|             E8|       S|   5|null|New York, NY / It...|
|     1|       1|Chambers, Mrs. No...|female|  33.0|    1|    0|          113806|    53.1|             E8|       S|   5|null|New York, NY / It...|
|     1|       1|Chaudanson, Miss....|female|  36.0|    0|    0|        PC 17608| 262.375|            B61|       C|   4|null|                null|
|     1|       1|Cherry, Miss. Gladys|female|  30.0|    0|    0|          110152|    86.5|            B77|       S|   8|null|     London, England|
|     1|       1|Chevre, Mr. Paul ...|  male|  45.0|    0|    0|        PC 17594|    29.7|             A9|       C|   7|null|       Paris, France|
|     1|       1|Chibnall, Mrs. (E...|female|  null|    0|    1|          113505|    55.0|            E33|       S|   6|null|St Leonards-on-Se...|
|     1|       0|Chisholm, Mr. Rod...|  male|  null|    0|    0|          112051|     0.0|           null|       S|null|null|Liverpool, Englan...|
|     1|       0|Clark, Mr. Walter...|  male|  27.0|    1|    0|           13508|136.7792|            C89|       C|null|null|     Los Angeles, CA|
|     1|       1|Clark, Mrs. Walte...|female|  26.0|    1|    0|           13508|136.7792|            C89|       C|   4|null|     Los Angeles, CA|
|     1|       1|Cleaver, Miss. Alice|female|  22.0|    0|    0|          113781|  151.55|           null|       S|  11|null|                null|
|     1|       0|Clifford, Mr. Geo...|  male|  null|    0|    0|          110465|    52.0|            A14|       S|null|null|       Stoughton, MA|
|     1|       0|Colley, Mr. Edwar...|  male|  47.0|    0|    0|            5727| 25.5875|            E58|       S|null|null|        Victoria, BC|
|     1|       1|Compton, Miss. Sa...|female|  39.0|    1|    1|        PC 17756| 83.1583|            E49|       C|  14|null|        Lakewood, NJ|
|     1|       0|Compton, Mr. Alex...|  male|  37.0|    1|    1|        PC 17756| 83.1583|            E52|       C|null|null|        Lakewood, NJ|
|     1|       1|Compton, Mrs. Ale...|female|  64.0|    0|    2|        PC 17756| 83.1583|            E45|       C|  14|null|        Lakewood, NJ|
|     1|       1|Cornell, Mrs. Rob...|female|  55.0|    2|    0|           11770|    25.7|           C101|       S|   2|null|        New York, NY|
|     1|       0|Crafton, Mr. John...|  male|  null|    0|    0|          113791|   26.55|           null|       S|null|null|       Roachdale, IN|
|     1|       0|Crosby, Capt. Edw...|  male|  70.0|    1|    1|       WE/P 5735|    71.0|            B22|       S|null| 269|       Milwaukee, WI|
|     1|       1|Crosby, Miss. Har...|female|  36.0|    0|    2|       WE/P 5735|    71.0|            B22|       S|   7|null|       Milwaukee, WI|
|     1|       1|Crosby, Mrs. Edwa...|female|  64.0|    1|    1|          112901|   26.55|            B26|       S|   7|null|       Milwaukee, WI|
|     1|       0|Cumings, Mr. John...|  male|  39.0|    1|    0|        PC 17599| 71.2833|            C85|       C|null|null|        New York, NY|
|     1|       1|Cumings, Mrs. Joh...|female|  38.0|    1|    0|        PC 17599| 71.2833|            C85|       C|   4|null|        New York, NY|
|     1|       1|Daly, Mr. Peter D...|  male|  51.0|    0|    0|          113055|   26.55|            E17|       S| 5 9|null|          Lima, Peru|
|     1|       1|Daniel, Mr. Rober...|  male|  27.0|    0|    0|          113804|    30.5|           null|       S|   3|null|    Philadelphia, PA|
|     1|       1|Daniels, Miss. Sarah|female|  33.0|    0|    0|          113781|  151.55|           null|       S|   8|null|                null|
|     1|       0|Davidson, Mr. Tho...|  male|  31.0|    1|    0|      F.C. 12750|    52.0|            B71|       S|null|null|        Montreal, PQ|
|     1|       1|Davidson, Mrs. Th...|female|  27.0|    1|    2|      F.C. 12750|    52.0|            B71|       S|   3|null|        Montreal, PQ|
|     1|       1|Dick, Mr. Albert ...|  male|  31.0|    1|    0|           17474|    57.0|            B20|       S|   3|null|         Calgary, AB|
|     1|       1|Dick, Mrs. Albert...|female|  17.0|    1|    0|           17474|    57.0|            B20|       S|   3|null|         Calgary, AB|
|     1|       1|Dodge, Dr. Washin...|  male|  53.0|    1|    1|           33638| 81.8583|            A34|       S|  13|null|   San Francisco, CA|
|     1|       1|Dodge, Master. Wa...|  male|   4.0|    0|    2|           33638| 81.8583|            A34|       S|   5|null|   San Francisco, CA|
|     1|       1|Dodge, Mrs. Washi...|female|  54.0|    1|    1|           33638| 81.8583|            A34|       S|   5|null|   San Francisco, CA|
|     1|       0|Douglas, Mr. Walt...|  male|  50.0|    1|    0|        PC 17761| 106.425|            C86|       C|null|  62|Deephaven, MN / C...|
|     1|       1|Douglas, Mrs. Fre...|female|  27.0|    1|    1|        PC 17558|247.5208|        B58 B60|       C|   6|null|        Montreal, PQ|
|     1|       1|Douglas, Mrs. Wal...|female|  48.0|    1|    0|        PC 17761| 106.425|            C86|       C|   2|null|Deephaven, MN / C...|
|     1|       1|"Duff Gordon, Lad...|female|  48.0|    1|    0|           11755|    39.6|            A16|       C|   1|null|      London / Paris|
|     1|       1|"Duff Gordon, Sir...|  male|  49.0|    1|    0|        PC 17485| 56.9292|            A20|       C|   1|null|      London / Paris|
|     1|       0|Dulles, Mr. Willi...|  male|  39.0|    0|    0|        PC 17580|    29.7|            A18|       C|null| 133|    Philadelphia, PA|
|     1|       1|Earnshaw, Mrs. Bo...|female|  23.0|    0|    1|           11767| 83.1583|            C54|       C|   7|null|Mt Airy, Philadel...|
|     1|       1|Endres, Miss. Car...|female|  38.0|    0|    0|        PC 17757| 227.525|            C45|       C|   4|null|        New York, NY|
|     1|       1|Eustis, Miss. Eli...|female|  54.0|    1|    0|           36947| 78.2667|            D20|       C|   4|null|       Brookline, MA|
|     1|       0|Evans, Miss. Edit...|female|  36.0|    0|    0|        PC 17531| 31.6792|            A29|       C|null|null|        New York, NY|
|     1|       0|  Farthing, Mr. John|  male|  null|    0|    0|        PC 17483|221.7792|            C95|       S|null|null|                null|
|     1|       1|Flegenheim, Mrs. ...|female|  null|    0|    0|        PC 17598| 31.6833|           null|       S|   7|null|        New York, NY|
|     1|       1|Fleming, Miss. Ma...|female|  null|    0|    0|           17421|110.8833|           null|       C|   4|null|                null|
|     1|       1|"Flynn, Mr. John ...|  male|  36.0|    0|    0|        PC 17474| 26.3875|            E25|       S|   5|null|        Brooklyn, NY|
|     1|       0|Foreman, Mr. Benj...|  male|  30.0|    0|    0|          113051|   27.75|           C111|       C|null|null|        New York, NY|
|     1|       1|Fortune, Miss. Al...|female|  24.0|    3|    2|           19950|   263.0|    C23 C25 C27|       S|  10|null|        Winnipeg, MB|
|     1|       1|Fortune, Miss. Et...|female|  28.0|    3|    2|           19950|   263.0|    C23 C25 C27|       S|  10|null|        Winnipeg, MB|
|     1|       1|Fortune, Miss. Ma...|female|  23.0|    3|    2|           19950|   263.0|    C23 C25 C27|       S|  10|null|        Winnipeg, MB|
|     1|       0|Fortune, Mr. Char...|  male|  19.0|    3|    2|           19950|   263.0|    C23 C25 C27|       S|null|null|        Winnipeg, MB|
|     1|       0|   Fortune, Mr. Mark|  male|  64.0|    1|    4|           19950|   263.0|    C23 C25 C27|       S|null|null|        Winnipeg, MB|
|     1|       1|Fortune, Mrs. Mar...|female|  60.0|    1|    4|           19950|   263.0|    C23 C25 C27|       S|  10|null|        Winnipeg, MB|
|     1|       1|Francatelli, Miss...|female|  30.0|    0|    0|        PC 17485| 56.9292|            E36|       C|   1|null|                null|
|     1|       0|Franklin, Mr. Tho...|  male|  null|    0|    0|          113778|   26.55|            D34|       S|null|null|Westcliff-on-Sea,...|
|     1|       1|Frauenthal, Dr. H...|  male|  50.0|    2|    0|        PC 17611|  133.65|           null|       S|   5|null|        New York, NY|
|     1|       1|Frauenthal, Mr. I...|  male|  43.0|    1|    0|           17765| 27.7208|            D40|       C|   5|null|        New York, NY|
|     1|       1|Frauenthal, Mrs. ...|female|  null|    1|    0|        PC 17611|  133.65|           null|       S|   5|null|        New York, NY|
|     1|       1|Frolicher, Miss. ...|female|  22.0|    0|    2|           13568|    49.5|            B39|       C|   5|null| Zurich, Switzerland|
|     1|       1|Frolicher-Stehli,...|  male|  60.0|    1|    1|           13567|    79.2|            B41|       C|   5|null| Zurich, Switzerland|
|     1|       1|Frolicher-Stehli,...|female|  48.0|    1|    1|           13567|    79.2|            B41|       C|   5|null| Zurich, Switzerland|
|     1|       0|    Fry, Mr. Richard|  male|  null|    0|    0|          112058|     0.0|           B102|       S|null|null|                null|
|     1|       0|Futrelle, Mr. Jac...|  male|  37.0|    1|    0|          113803|    53.1|           C123|       S|null|null|        Scituate, MA|
|     1|       1|Futrelle, Mrs. Ja...|female|  35.0|    1|    0|          113803|    53.1|           C123|       S|   D|null|        Scituate, MA|
|     1|       0|   Gee, Mr. Arthur H|  male|  47.0|    0|    0|          111320|    38.5|            E63|       S|null| 275|St Anne's-on-Sea,...|
|     1|       1|Geiger, Miss. Amalie|female|  35.0|    0|    0|          113503|   211.5|           C130|       C|   4|null|                null|
|     1|       1|Gibson, Miss. Dor...|female|  22.0|    0|    1|          112378|    59.4|           null|       C|   7|null|        New York, NY|
|     1|       1|Gibson, Mrs. Leon...|female|  45.0|    0|    1|          112378|    59.4|           null|       C|   7|null|        New York, NY|
|     1|       0|  Giglio, Mr. Victor|  male|  24.0|    0|    0|        PC 17593|    79.2|            B86|       C|null|null|                null|

In [1]:
import pandas as pd

data = pd.read_csv("../datasets/titanic/titanic3.csv")

data.head

   pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chestervill